export default {
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "rgba(0,0,0,0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    background: "#2f3643",
    padding: 24,
    borderRadius: 8,
    width: "90%",
    maxWidth: 480,
    color: "#e0e0e0",
    overflowY: "auto",
    maxHeight: "90%",
  },
  tfContainer: {
    width: "60%",
    marginBottom: "30px;",
    display: "flex",
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    width: "100%",
    justifyContent: "space-evenly",
  },
  tfContainerVertical: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
    width: "100%",
    marginBottom: 0,
  },

  tfField: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  field: { display: "flex", flexDirection: "column", marginBottom: 12 },
  label: { marginBottom: 4, padding: "0px 0px", fontSize: 14 },
  select: {
    padding: 8,
    borderRadius: 4,
    border: "1px solid #555",
    background: "#1e222b",
    color: "#e0e0e0",
  },
  selectItem: {
    paddingRight: 16,
  },
  checkboxRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 16 },
  submit: {
    marginTop: 8,
    padding: "10px 20px",
    border: "none",
    borderRadius: 4,
    background: "#4caf50",
    color: "#fff",
    fontSize: 16,
    cursor: "pointer",
  },
};
